# Generated by Django 3.2.7 on 2021-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
